hamru/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/',
    include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
    path('',include("post.urls",namespace="post")),
    path('',include('chatbox.urls',namespace="chatroom"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from . import views

app_name = 'images'

urlpatterns = [
    path('', views.image_list, name='list'),
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/',
         views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
]

post/urls.py
from django.urls import path
from . import views
app_name = "post"


urlpatterns = [
    path('',views.HomeView.as_view(),name='home'),
    path('post/<int:post_id>/<slug:post_slug>/',views.DetailView.as_view(),name='detail'),
    path('post/delete/<int:post_id>',views.PostDeleteView.as_view(),name='post_delete'),
    path('post/update/<int:post_id>',views.PostUpdateView.as_view(),name='post_update'),
    # path('post/create/',views.PostCreateView.as_view(),name='post_create'),
    path('post/create/',views.create_post,name='post_create'),
    path('reply/<int:post_id>/<int:comment_id>/',views.ReplyCommentView.as_view(),name="reply_comment"),
    # path('like/<int:post_id>/',views.PostLikeView.as_view(),name="post_like"),
    path('like/<int:post_id>/',views.post_like,name="post_like")
   
]

images/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse


class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='images_created',
                             on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,
                            blank=True)
    url = models.URLField(blank=True,null=True)
    image = models.ImageField(upload_to='images/%Y/%m/%d/')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True,
                               db_index=True)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name='images_liked',
                                        blank=True)
    total_likes = models.PositiveIntegerField(db_index=True,
                                              default=0)
    total_views = models.PositiveIntegerField(default=0)
    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id, self.slug])

images/forms.py
from django import forms
from .models import Image
from django.utils.text import slugify
from urllib import request
from django.core.files.base import ContentFile


class ImageCreateForm(forms.ModelForm):

    class Meta:
        model = Image
        fields = ('title', 'description','image')
        widgets = {
            'url': forms.HiddenInput,
            'image': forms.FileInput(attrs={'onchange': 'previewImage(event)'})
        }

images/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import ImageCreateForm
from django.contrib import messages
from .models import Image
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from common.decorators import ajax_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from actions.utils import create_action
from post.forms import PostSearchForm


@login_required
def image_create(request):
    if request.method == 'POST':
        form = ImageCreateForm(request.POST,request.FILES)
        if form.is_valid():
            new_item = form.save(commit=False)
            new_item.user = request.user
            new_item.save()
            create_action(request.user, 'uploaded image', new_item)
            messages.success(request, 'Image added successfully!')
            return redirect(new_item.get_absolute_url())
    else:
        form = ImageCreateForm()
        return render(request, 'images/image/create.html',
                      {'section': 'images', 'form': form})













def image_detail(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug)
    image.total_views += 1
    image.save()
    return render(request,
                  'images/image/detail.html',
                  {'section': 'images',
                   'image': image
                })

@ajax_required
@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user)
                create_action(request.user, 'likes', image)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except:
            pass

    return JsonResponse({'status': 'error'})

@login_required
def image_list(request):
    # images = Image.objects.all()
    # Denormalization Example
    images = Image.objects.order_by('-total_likes')
    # Normal DB but hard query
    # from django.db.models import Count
    # images = Image.objects.annotate(
    #     total_likes=Count('users_like')).order_by('-total_likes')
    search = PostSearchForm()
    if request.GET.get('search'):
        images = images.filter(description__contains=request.GET['search'])
    paginator = Paginator(images, 30)
    page = request.GET.get("page")
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        images = paginator.page(1)
    except EmptyPage:
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return HttpResponse('')
        images = paginator.page(paginator.num_pages)

    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        return render(request, 'images/image/list_ajax.html',
                      {'section': 'images', 'images': images})

    return render(request, 'images/image/list.html',
                      {'section': 'images', 'images': images,'search':search})

images/templates/images/image/create.html
{% extends "base.html" %}

{% block title %}Upload an image{% endblock %}

{% block content %}
  <h1>Upload an image</h1>
  <form method="post" enctype="multipart/form-data">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Upload it!">
  </form>
{% endblock %}

images/templates/images/image/detail.html
{% extends "base.html" %}

{% block title %}{{ image.title }}{% endblock %}

{% block content %}
  <h1>{{ image.title }}</h1>
  {% load thumbnail %}

  <a href="{{ image.image.url }}">
    <img src="{% thumbnail image.image 350x0 %}" class="image-detail">
  </a>

  {% with total_likes=image.users_like.count users_like=image.users_like.all %}
    <div class="image-info">
      <div>
        <span class="count">
          <span class="total">{{ total_likes }}</span>
          like{{ total_likes|pluralize }}
        </span>
        <span class="count">{{ image.total_views }} view{{ image.total_views|pluralize }}</span>
        <a href="#" data-id="{{ image.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
          {% if request.user not in users_like %}
            Like
          {% else %}
            Unlike
          {% endif %}
        </a>
      </div>
      {{ image.description|linebreaks }}
    </div>

    <div class="image-likes">
      {% for user in users_like %}
     
        <div>
          {% if user.profile.photo %}
          <img src="{{ user.profile.photo }}">
          {% else %}
          <img src="https://via.placeholder.com/200" class="avatar img-circle img-thumbnail" alt="avatar">
          {% endif %}
          <p>{{ user.first_name }}</p>
        </div>
     
      {% empty %}
        Nobody likes this image yet.
      {% endfor %}
    </div>
  {% endwith %}
{% endblock %}

{% block domready %}

  $('a.like').click(function(e) {
    e.preventDefault();
    $.post('{% url "images:like" %}',
      {
        id: $(this).data('id'),
        action: $(this).data('action')
      },
      function(data){
        if (data['status'] == 'ok')
        {
          var previous_action = $('a.like').data('action');
          $('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');
          $('a.like').text(previous_action == 'like' ? 'Unlike' : 'Like');

          var previous_likes = parseInt($('span.count .total').text());
          $('span.count .total').text(previous_action == 'like' ? previous_likes + 1 : previous_likes - 1);
        }
      }

    );
  });

{% endblock %}

images/templates/images/image/list.html
{% extends "base.html" %}

{% block title %}Images Uploaded{% endblock %}

{% block content %}
  <h1>Images Uploaded</h1>
  <form id="form" method="get"> 
    {{search.as_p}}
    {% comment %} <input name="search" type="search" id="query" name="q" placeholder="Search..."> {% endcomment %}
    <button class="btn btn-success" type="submit">Search</button>
  </form> 
  <br>
  <div id="image-list">
    {% include "images/image/list_ajax.html" %}
  </div>
{% endblock %}

{% block domready %}
  var page = 1;
  var empty_page = false;
  var block_request = false;

  $(window).scroll(function() {
    var margin = $(document).height() - $(window).height() - 200;
    if  ($(window).scrollTop() > margin && empty_page == false && block_request == false) {
        block_request = true;
        page += 1;
        $.get('?page=' + page, function(data) {
            if(data == '') {
                empty_page = true;
            }
            else {
                block_request = false;
                $('#image-list').append(data)
            }
        });
    }
  });
{% endblock %}

images/templates/images/image/list_ajax.html
{% load thumbnail %}

{% for image in images %}
  <div class="image">
    <a href="{{ image.get_absolute_url }}">
      {% thumbnail image.image 200x200 crop="smart" as im %}
      <img src="{{ im.url }}">
      
    </a>
   
    <div class="info">
      <a href="{{ image.get_absolute_url }}" class="title">
        {{ image.title }}
      </a>
    </div>
  </div>
  {% comment %} {% for post in text_post %}
  <a href="{% url 'post:detail' post.id post.slug %}" class="card-body">{{post.body|truncatewords:5}}</a>
  
  {% endfor %} {% endcomment %}
{% endfor %}