hamru/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/',
    include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
    path('',include("post.urls",namespace="post")),
    path('',include('chatbox.urls',namespace="chatroom"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views
app_name = "post"


urlpatterns = [
    path('',views.HomeView.as_view(),name='home'),
    path('post/<int:post_id>/<slug:post_slug>/',views.DetailView.as_view(),name='detail'),
    path('post/delete/<int:post_id>',views.PostDeleteView.as_view(),name='post_delete'),
    path('post/update/<int:post_id>',views.PostUpdateView.as_view(),name='post_update'),
    # path('post/create/',views.PostCreateView.as_view(),name='post_create'),
    path('post/create/',views.create_post,name='post_create'),
    path('reply/<int:post_id>/<int:comment_id>/',views.ReplyCommentView.as_view(),name="reply_comment"),
    # path('like/<int:post_id>/',views.PostLikeView.as_view(),name="post_like"),
    path('like/<int:post_id>/',views.post_like,name="post_like")
   
]

post/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.



class Post(models.Model):
    body=models.TextField()
    slug=models.SlugField()
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    user= models.ForeignKey(User,on_delete=models.CASCADE,related_name='posts')

    class Meta:
        ordering=('-created',)
     
    def __str__(self):
        return f'{self.slug} - {self.updated}'
    
    def get_absolute_url(self):
       
       return reverse('home:detail', args={self.id , self.slug})
    


class Comment(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='usercomments')
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='postcomments')
    reply = models.ForeignKey('self',on_delete=models.CASCADE,related_name='replycomments',blank=True,null=True)
    is_reply = models.BooleanField(default=False)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f'{self.user} - {self.body[:30]}'
    


class Vote(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='uservotes')
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='postvotes')

    def __str__(self):
        return f'{self.user} liked {self.post.slug}'
    

post/forms.py
from django import forms
from .models import Post,Comment

class PostUpdate(forms.ModelForm):
    class Meta:
       model=Post
       fields = ('body',)
       labels={
            'body':'Update your post'
        }
       widget = {
           'body':forms.Textarea(attrs={"class":"form-control","row":'3'})
       }




class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
       
        widgets = {
            'body':forms.Textarea(attrs={'class':'form-control'})
        }


class CommentReplyForm(forms.ModelForm):
    class  Meta:
        model = Comment
        fields = ('body',)



class PostSearchForm(forms.Form):
    search = forms.CharField()

post/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import  HttpResponse
from django.views import View
from .models import Post,Comment
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from .forms import PostUpdate, CommentCreateForm,CommentReplyForm, PostSearchForm
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .models import Vote
from django.http import JsonResponse
from django.contrib.auth.models import User


class HomeView(LoginRequiredMixin,View):
    form_class = PostSearchForm
    def get(self,request):
        posts = Post.objects.all()
        user = User.objects.all()
        if request.GET.get('search'):
            posts = posts.filter(body__contains=request.GET['search'])
           
        return render(request, 'post/index.html',{'posts':posts,'search':self.form_class,'user':user})
    




class DetailView(View):

    form_class = CommentCreateForm
    form_class_reply = CommentReplyForm
    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post, id =kwargs['post_id'], slug = kwargs['post_slug'])
        return super().setup(request, *args, **kwargs)
    
    def get(self,request,*args,**kwargs):
        comments = self.post_instance.postcomments.filter(is_reply = False)
        # vote = Vote.objects.create(post=self.post_instance, user=request.user)
        return render(request,'post/detail.html',{'post':self.post_instance,'comments':comments,'form':self.form_class,'reply_form':self.form_class_reply})
    # @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid:
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = self.post_instance
            new_comment.save()
            messages.success(request,'your comment has been submitted successfully','success')
            return redirect('post:detail',self.post_instance.id,self.post_instance.slug)
        

class PostDeleteView(LoginRequiredMixin,View):
    def get(self,request,post_id):
        posts = get_object_or_404(Post,id = post_id)
        
        if posts.user.id == request.user.id:
            posts.delete()
            messages.success(request,'Deleted successfully','success')
        else:
            messages.error(request,'Can\'t be deleted','danger')
        return redirect('post:home')
    

class PostUpdateView(View):
    form_class = PostUpdate
    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post,id=kwargs['post_id'])

        return super().setup(request, *args, **kwargs)
    def dispatch(self, request, *args, **kwargs):
        post = self.post_instance
        # post = Post.objects.get(id=kwargs['post_id'])
        if not post.user.id == request.user.id:
            messages.error(request,'Can\'t be update','danger')
            return redirect('post:home')
        return super().dispatch(request, *args, **kwargs)
    def get(self,request,post_id):
        post = self.post_instance

        # post = Post.objects.get(id = post_id)
        form = self.form_class(instance = post)
        return render(request,'post/update.html',{'form':form})
    def post(self,request,post_id):
        post = self.post_instance

    #   post = Post.objects.get(id = post_id)
        form = self.form_class(request.POST,instance=post)
        if form.is_valid:
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data['body'][:30])
            new_post.save()
            messages.success(request,'updated successfully','success')
            return redirect('post:detail',post.id,post.slug)

# class PostCreateView(LoginRequiredMixin,View):
#     form_class = PostUpdate
#     def get(self,request,*args,**kwargs):
#         form = self.form_class
#         return(request,'post/create.html',{'form':form})
#     def post(self,request,*args,**kwargs):
#         form = self.form_class(request.POST)
#         if form.is_valid:
#             new_post = form.save(commit=False)
#             new_post.slug = slugify(form.cleaned_data['body'][:30])
#             new_post.user = request.user
#             new_post.save()
#             messages.success(request,'Post created','success')
#             return redirect('post:detail',new_post.id, new_post.slug) 
        
def create_post(request):
    if request.method == 'POST':
        form = PostUpdate(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.user = request.user
            new_post.slug = slugify(form.cleaned_data['body'][:30])
            new_post.save()
            return redirect('post:detail',new_post.id, new_post.slug)
    else:
        form = PostUpdate()
    return render(request, 'post/create.html', {'form': form,"section":"text-post"})





class ReplyCommentView(LoginRequiredMixin,View):
    form_class = CommentReplyForm
    def post(self,request,post_id,comment_id):
         post = get_object_or_404(Post,id = post_id)
         comment = get_object_or_404(Comment,id = comment_id)
         form = self.form_class(request.POST)
         if form.is_valid():
            reply = form.save(commit = False)
            reply.user = request.user
            reply.post = post
            reply.reply = comment
            reply.is_reply = True
            reply.save()
            messages.success(request,'you replied sucessfully','success')
         return redirect('post:detail', post.id, post.slug)




# class PostLikeView(LoginRequiredMixin,View):
#     def get(self,request,post_id):
#         post = get_object_or_404(Post,id = post_id)
#         like = Vote.objects.filter(post = post,user = request.user)
#         if like.exists():
#             vote = "dislike"
#         else:
#             Vote.objects.create(post = post,user = request.user)
#             vote = "like"
#         return redirect('post:detail', post.id, post.slug)







def post_like(request, post_id):
    if request.method == 'POST':
        post = get_object_or_404(Post, id=post_id)
        
        if Vote.objects.filter(post=post, user=request.user).exists():
            return JsonResponse({'status': 'error', 'message': 'You have already liked this post.'})
        Vote.objects.create(post=post, user=request.user)
        likes_count = Vote.objects.filter(post=post).count()
        return JsonResponse({'status': 'success', 'likes_count': likes_count})
    else:
        return JsonResponse({'status': 'error', 'message': 'Invalid request method.'})

post/templates/post/create.html
{% extends "base.html" %}
{% block content %}
 {% comment %} <form action="" method="POST" novalidate>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="btn btn-primary" value="Create">
</form>  {% endcomment %}
<div class="container my-4">
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="postContent">What's on your mind?</label>
                            <textarea name="body" class="form-control" id="postContent" rows="3"></textarea>
                        </div>
                        <input type="submit" class="btn btn-primary" value="Post">

                    </form>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock  %}

post/templates/post/detail.html
{% extends 'base.html' %}
{% block content %}









         <div class="container mt-5">
            <!-- Post content -->
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">{{post.user.username}} - {{post.updated |date:'Y-M'}}</h5>
                <span class="text-muted" id="like-count">Likes: {{ post.postvotes.count }} </span>
                <p class="card-text">{{post.body}}</p>
                <!-- Like button -->
                <button id="like-button" data-id="{{ post_id }}" type="button" class="liked btn btn-outline-secondary mr-2">
                {% if request.user.id in vote.user.id %}
                    Like
                  {% else %}
                    Unlike
                  {% endif %}
                </button>
                <!-- Number of likes -->
                
                <!-- Update button -->
                {% if request.user.id == post.user.id  %}
                <a href="{% url 'post:post_update' post.id %}" class="btn btn-outline-primary mr-2">
                  <i class="fa fa-edit"></i> Update
                </a>
                <!-- Delete button -->
                <a href="{% url 'post:post_delete' post.id %}" class="btn btn-outline-danger">
                  <i class="fa fa-trash"></i> Delete
                </a>
                {% endif %}
              </div>
            </div>
        
            <!-- Comment form -->
            {% if request.user.is_authenticated %}
            <form method="post" class="mt-4">
                {% csrf_token %}
              <div class="form-group">
                
        
                <label for="comment">Add a comment:</label>
                <textarea name="body" class="form-control" id="comment" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            {% else %}
            <p class="alert alert-danger">only registered users can Comment.</p>
            {% endif %}
            <!-- Comments section -->
            <div class="mt-4">
              <h5>Comments:</h5>
              <!-- Comment 1 -->
              <p>{{comments.count}} comment(S)</p>  
             {% for comment in comments  %}
              <div class="card mt-3">
                <div class="card-body">
                    <p class="card-header">{{comment.user}}|{{comment.created|timesince}} </p>
                    <p class="card-body">{{comment.body}}</p>
                    
                    {% if request.user.is_authenticated %}
                    <form action="{% url 'post:reply_comment' post.id comment.id %}" method="post">
                        {% csrf_token %}
                        <textarea name="body" class="form-control" id="comment" rows="3"></textarea>

                        {% comment %} {{reply_form.as_p }} {% endcomment %}
                        <input type="submit" class="btn btn-primary" value='reply'>
                    </form> 
                    {% endif %}
                    {% with replies=comment.replycomments.all  %}
                    {% for reply in replies %}
                       <p class="bg-white p-3 m-2">{{reply.user}} - {{reply.body}} </p>
                    {% endfor %}
                    {% endwith %}  
                </div>
                <br>
            {% empty %}
            <hr>
            no cooment yet
             {% endfor %} 
                 




















{% endblock  %}

 {% block js %}
<script>
    $(document).ready(function() {
        
        $('#like-button').click(function() {
          var post_id = $(this).data('post-id');
          var post_slug = '{{ post.slug }}';
      
          var button = $(this);
          var is_liked = button.hasClass('liked');
      
          $.ajax({
            method: 'POST',
            url: '{% url "post:post_like" post.id %}',
            data: {
              'post_id': post_id,
              'post_slug': post_slug,
              'is_liked': is_liked,
              'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            success: function(data) {
              var likes_count = data.likes_count;
              button.find('span.count').text(likes_count);
              if (is_liked) {
                button.text('Like');
                button.removeClass('liked');
              } else {
                button.text('Unlike');
                button.removeClass('unliked');
                
              }
            }
          });
        });
      });
      
</script>
{% endblock js %}  



  

post/templates/post/index.html
{% extends 'base.html' %}

{% block content %}
{% comment %} <h1>Index page</h1>  
<div class="card">
    {% for post in posts %}
    <a href="{% url 'post:detail' post.id post.slug %}" class="card-body">{{post.body|truncatewords:5}}</a>
    
    {% endfor %}
</div> {% endcomment %}

<div class="container">
    <h1 class="text-center my-4">All text Posts</h1>
    <form id="form" method="get"> 
        {{search.as_p}}
        {% comment %} <input name="search" type="search" id="query" name="q" placeholder="Search..."> {% endcomment %}
        <button class="btn btn-success" type="submit">Search</button>
      </form> 
    {% for post in posts %}

    <div class="card mb-3">
      <div class="card-body">
        <a href="{% url 'post:detail' post.id post.slug %}" class="card-body">{{post.body|truncatewords:5}}</a>
        <p class="card-text"><small class="text-muted">{{post.created}}</small></p>
      </div>
      {% endfor %}
    </div>
</div>
{% endblock %}

post/templates/post/update.html
{% extends "base.html" %}
{% block content %}

 {% comment %} <form action="" method="post" novalidate>
    {% csrf_token %}
   
    <button class="btn btn-info" type="submit">Update</button>
</form>   {% endcomment %}


<div class="container my-4">
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            {{form.as_p}}
                            {% comment %} <label for="postContent">Update your post</label>
                            <textarea name="body" class="form-control" id="postContent" rows="3"></textarea> {% endcomment %}
                        </div>
                        <input type="submit" class="btn btn-primary" value="Update">

                    </form>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock  %}